### ISSUE TITLE
Offtopic: how to use an own action ?

### ISSUE THREAD

**Issue by hannesa2** [gradle-update/update-gradle-wrapper-action#47]
Hi, it seems you know how to handle own actions, so I ask you

I want to use an own forked [action](https://github.com/hannesa2/action-android/commit/c7f247f4fc3c14310c8bae8899a2d3c344e22ef4), because origin maintainer doesn't approve/merge [my pull request](https://github.com/Malinskiy/action-android/pull/24)

So I made an own tag `0.0.7.1` in my repo
<img width="579" alt="image" src="https://user-images.githubusercontent.com/3314607/97077475-57851b80-15e4-11eb-8783-3d11009dff13.png"> with a new release https://github.com/hannesa2/action-android/releases/tag/0.0.7.1

But when I use it, https://github.com/AppDevNext/Logcat/pull/81/files 
`uses: hannesa2/action-android/install-sdk@release/0.0.7.1`

I run into
https://github.com/AppDevNext/Logcat/pull/81/checks?check_run_id=1301629466
<img width="838" alt="image" src="https://user-images.githubusercontent.com/3314607/97077532-d2e6cd00-15e4-11eb-8b5f-f1b9da6e2ba6.png">

Curious, it works with `0.0.7` !

I guess I miss one step, do you have clue how to make it work ?

**Comment by cristiangreco** [comment]
Hey @hannesa2, it seems that the file `install-sdk/lib/main.js` doesn't exist in your branch `release/0.0.7.1`.

I see the repository contains a file named `prepare-for-release.sh`, maybe you want to run that script in your new branch so that it builds the app and creates the `lib/main.js` script (which you then need to commit in the branch).

**Comment by hannesa2** [comment]
Thank you, it was a point into the right direction
